#ifndef SIMULATORLOGCONFIG_H
#define SIMULATORLOGCONFIG_H

//Common log config
#define SIMULATOR_DEBUG_ENABLED 1
#define SIMULATOR_LOG_ENTRY_ENABLED 1
//ats related log config
#define ATS_SIMULATOR_DEBUG_ENABLED 1
#define ATS_SIMULATOR_LOG_ENTRY_ENABLED 1


#if SIMULATOR_DEBUG_ENABLED
#if SIMULATOR_LOG_ENTRY_ENABLED
#define SIMULATOR_LOG_ENTRY() qDebug("Entry")
#else //SIMULATOR_LOG_ENTRY_ENABLED
#define SIMULATOR_LOG_ENTRY()
#endif
#define SIMULATOR_DEBUG       qDebug
#define SIMULATOR_INFO        qInfo
#define SIMULATOR_WARN        qWarning
#else //SIMULATOR_DEBUG_ENABLED
#define SIMULATOR_LOG_ENTRY()
#define SIMULATOR_DEBUG       QT_NO_QDEBUG_MACRO
#define SIMULATOR_INFO        QT_NO_QDEBUG_MACRO
#define SIMULATOR_WARN        QT_NO_QDEBUG_MACRO
#endif


#if ATS_SIMULATOR_DEBUG_ENABLED
#if ATS_SIMULATOR_LOG_ENTRY_ENABLED
#define ATS_SIMULATOR_LOG_ENTRY() qDebug("Entry")
#else //ATS_SIMULATOR_LOG_ENTRY_ENABLED
#define ATS_SIMULATOR_LOG_ENTRY()
#endif
#define ATS_SIMULATOR_DEBUG       qDebug
#define ATS_SIMULATOR_INFO        qInfo
#define ATS_SIMULATOR_WARN        qWarning
#else //ATS_SIMULATOR_DEBUG_ENABLED
#define ATS_SIMULATOR_LOG_ENTRY()
#define ATS_SIMULATOR_DEBUG       QT_NO_QDEBUG_MACRO
#define ATS_SIMULATOR_INFO        QT_NO_QDEBUG_MACRO
#define ATS_SIMULATOR_WARN        QT_NO_QDEBUG_MACRO
#endif


#endif // SIMULATORLOGCONFIG_H
